metrics_to_publish:
  array_capacity_total: 
  array_capacity_used: 
  array_status: 
  available_spare: 
  available_spare_threshold: 
  average_io_size: 
  average_latency: 
  bandwidth_device: 
  capacity_array: 
  capacity_volume: 
  controller_busy_time_lower: 
  controller_busy_time_upper: 
  critical_temperature_time: 
  iops: 
  iops_read: 
  iops_write: 
  number_of_io_reqs_per_sec: 
  number_of_read_bytes_per_sec: 
  number_of_reads_per_sec: 
  number_of_write_bytes_per_sec: 
  number_of_writes_per_sec: 
  percentage used: 
  power_cycle_error_lower: 
  power_cycle_error_upper: 
  power_on_hour_lower: 
  power_on_hour_upper: 
  read_bytes_per_sec_host: 
  read_bytes_per_sec_port: 
  read_iops_host: 
  read_iops_port: 
  read_latency: 
  soft_media_error_lower: 
  soft_media_error_upper: 
  state_array: 
  state_volume: 
  temperature: 
  unsafe_shutdowns_lower: 
  unsafe_shutdowns_upper: 
  uptime_sec: 
  used_array: 
  used_volume: 
  warning_temperature_time: 
  write_bytes_per_sec_host: 
  write_bytes_per_sec_port: 
  write_iops_host: 
  write_iops_port: 
  write_latency: 
